# Generated by Django 4.1.3 on 2023-02-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='lanlord',
            new_name='landlord',
        ),
        migrations.AlterField(
            model_name='home',
            name='has_garage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='home',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='home',
            name='is_furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='home',
            name='num_saves',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='home',
            name='num_views',
            field=models.IntegerField(default=0),
        ),
    ]
