# Generated by Django 4.1.6 on 2023-03-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_landlord_user_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
