# Generated by Django 4.1.6 on 2023-03-03 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_comments_comment_alter_comments_rating'),
        ('main', '0003_alter_home_landlord'),
    ]

    operations = [
    ]
