# Generated by Django 4.1.3 on 2023-03-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_merge_20230303_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='photos',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
